scripts/init/database/db_load.sh
scripts/init/database/migrations/001.do.sql
scripts/init/database/testdata/teams.csv
service/lib/ops/teamOps.js
service/routes/public/teams.js
service/routes/public/users.js
service/swagger.js
service/test/endToEnd/teamsTest.js
service/test/endToEnd/usersTest.js
service/test/lib/integration/teamOpsTest.js
service/test/lib/integration/userOpsTest.js

Fixes #247 
I have a question: how should the app behave if on creation is specified an id that already exists on the db?
At the moment we just return 500 bad implementation due to the db constraint, my feeling is that we should manage the error and return the proper status code and message.
@p16 how did you implement this on the users?
@feugy thoughts?

Make team id strings, allow to specify id on creation

---

service/lib/mapping.js
service/lib/ops/teamOps.js
service/swagger.js
service/test/endToEnd/teamsTest.js

Implements https://github.com/nearform/labs-authorization/issues/257
The team count counts the users in the team but not in subteams.

add users count per team

---

service/lib/ops/userOps.js
service/routes/public/users.js
service/test/endToEnd/usersTest.js
service/test/lib/integration/authorizeOpsTest.js
service/test/lib/integration/userOpsTest.js
service/test/routes/public/usersTest.js
service/test/utils.js

This PR removes the `teams` param from `PUT /users/{id}` endpoint.
The idea is that now that we have
```
PUT /teams/{id}/users
POST /teams/{id}/users
DELETE /teams/{id}/users
DELETE /teams/{id}/users/{userId}
```
we should work on teams members from those endpoints and not from the user update one.
/cc @feugy @marcopiraccini 
Ref. issue #275

Remove left over "teams" param in user update endpoint

---

service/test/lib/integration/teamOpsTest.js
service/test/utils.js

Notes:
- The refactor is not complete as many tests still rely on the global fixtures but I think tests are more stable now
- We should start using promises as it would really make the tests more readable. Nested callbacks are ok up to a point and I have gone a bit beyond that..
- I spent little time checking if all tests properly clean behind themselves so that may not be at 100% yet.

Remove hardcoded ids in tests

---

service/lib/mapping.js
service/lib/ops/teamOps.js
service/routes/public/teams.js
service/swagger.js
service/test/endToEnd/teamsTest.js
service/test/lib/integration/teamOpsTest.js

3 commits:
- return user count as number on the teams endpoint,
- return user count also on the get team endpoint,
- paginated users from team. Returns as metadata beside users also  currentPage, pageSize, totalPages, totalUsersCount

Issue 258 paginated team list users

---

service/test/endToEnd/authorization/usersTest.js

I opened this PR against my other PR so that changes to the code are clearer and it's hopefully easier to check if the new framework brings more clarity.
This PR currently contains the first step of such a framework: a function to build all initial records in one place. It is currently called `prepareTest` and returns an object intended to be later used to access created records (and in further iteration also dry-up the test definitions).
Two thing to note:
- Created records can be accessed by the key used in the records definition, but will have generic auto-generated ids
- Internally it still uses `lab.before` and `lab.after`, which I think is good for keeping everything in sync
At this time I'm seeking feedbacks on the type of approach and the "api definition" of the `prepareTest` …

Custom test framework

---

test/endToEnd/authorization/usersTest.js

This PR introduce the light framework for defining authentications tests. Like in the previous PR this is directed to my main PR and is intended to collect feedback on the style and usefulness of the framework.
One thing to notice: I had to introduce a form of interpolation for the values (i.e. policy.id, caller.id) because those records are created at run-time, after the definition of the tests.
Another possible solution would be to wrap the definitions inside a regular `lab.test`, i.e:
```js
const endpoint = BuildFor(lab, records)
.server(server)
.endpoint({
method: 'GET',
url: '/authorization/users/{{called.id}}',
headers: { authorization: '{{caller.id}}' }
})
lab.test('should authorize caller with policy for specific users', (done) => {
endpoint       
.withPolicy([{
Effect: 'Allow', …
```

Custom test framework 2

---

linter.js
package.json

This PR add the ability to run pre-commit linting only on staged files.
The output will be something like this
The flow is:
- git stash only [unstaged changes](https://github.com/nearform/labs-authorization/pull/297/files#diff-87d41a187bfa2e196628052abbf001a9R34) (with a [specific comment](https://github.com/nearform/labs-authorization/pull/297/files#diff-87d41a187bfa2e196628052abbf001a9R11))
- run linting [only on `.js` files](https://github.com/nearform/labs-authorization/pull/297/files#diff-87d41a187bfa2e196628052abbf001a9R47)
- report errors (if any)
- git pop if the initial stash was created (empty* stashes will not be created)
* if you have something staged an no other modification an empty stash is created anyway

Issue 265 pre commit hook only on staged files

---

src/routes/private/policies.js
src/swagger.js
test/endToEnd/authorization/testBuilder.js
test/endToEnd/authorization/usersTest.js
test/endToEnd/policiesTest.js
test/endToEnd/usersTest.js
test/lib/integration/authorizeOpsTest.js
test/lib/integration/organizationOpsTest.js
test/lib/integration/policyOpsTest.js
test/lib/integration/teamOpsTest.js

This PR changes the policy `statemets` property from a string to an object when creating or updating a policy.
Ref. issue #284

Add statemets as an object instead of a string in policy creation/update

---

src/lib/config/config.auth.js
src/lib/ops/teamOps.js
src/routes/public/teams.js
test/endToEnd/authorization/policiesTest.js
test/endToEnd/authorization/teamsTest.js
test/endToEnd/teamsTest.js
test/lib/unit/configAuthTest.js

Included fixes:
- fix policies resource string template
- return error on delete team only if specific team is not found (ignore descendants), this solves a race conditions
- return status code 200 on nest and unnest instead of 201
- fix auth params for remove policy from team (it was returning the wrong parameter for teamId)
Fixes #240

Complete authentication tests

---

src/lib/ops/authorizeOps.js
src/lib/ops/organizationOps.js
src/lib/ops/policyOps.js
src/lib/ops/teamOps.js
src/lib/ops/userOps.js
src/lib/ops/validation.js
src/routes/private/policies.js
src/routes/public/authorization.js
src/routes/public/organizations.js
src/routes/public/policies.js
src/routes/public/teams.js
src/routes/public/users.js
src/security/hapi-auth-validation.js
src/swagger.js
src/udaru.js
test/endToEnd/authorization/usersTest.js
test/endToEnd/authorizationTest.js
test/endToEnd/teamsTest.js
test/endToEnd/usersTest.js
test/lib/integration/authorizeOpsTest.js
test/lib/integration/organizationOpsTest.js
test/lib/integration/policyOpsTest.js
test/lib/integration/teamOpsTest.js
test/routes/public/authorizationTest.js
test/routes/public/policiesTest.js
test/routes/public/teamsTest.js
test/routes/public/usersTest.js

Hi all,
this PR is a WIP for now and it's done to get some feedback.
I've created the `udaru` module and move the validation objects into the `ops` modules.
The validation is exposed to the routes through a `validate` property on each `udaru` function:
```
udaru.listOrganizations <=== function 
udaru.listOrganizations.validate <==== Joi object for validation
```
The most advanced of the modules is the [`userOps` module](https://github.com/nearform/labs-authorization/pull/319/files#diff-2e3e1b7134f3e2b71f7da05921880cef). 
In it I've:
- regrouped all the validation rules into an object
- added the validation inside the functions 
- added the property `validate` to each function
Next steps:
- do the same for the other ops modules
- create a single file for validation rules definition
- make …

Issue 301 udaru module

---

database/migrations/001.do.sql
src/lib/ops/organizationOps.js
src/lib/ops/validation.js
test/endToEnd/organizationsTest.js
test/endToEnd/teamsTest.js
test/endToEnd/usersTest.js

Implementation of https://github.com/nearform/labs-authorization/issues/324
Changes:
- Org, Teams and User creation endpoints can have in payload: id exists, id exists but is undefined, id does not exist (it is generated internally), **id as empty string is rejected**. Changed Joi validation according to these,
- Org creation have no regex limitations,
- the Org id in DB is changed to VARCHAR(128) - it was VARCHAR(20),
- Updated tests and added tests according to the changes above.

POST users, teams, orgs functionality unification

---

src/lib/ops/policyOps.js
src/security/hapi-auth-validation.js
test/factory.js
test/lib/integration/authorizeOpsTest.js
test/lib/integration/policyOpsTest.js

This PR includes the following fixes/features:
- fix a bug in the listAllUserPolicies query that messed with team policies (returning policy not assigned to the user team)
- scope the listAllUserPolicies query by organisation
- optimize the listAllUserPolicies query
- expand factory to support team policies, team trees and provide default policy data
- do not scope policy removal from users and teams by org (when deleting an org all association to it are now removed)
- use the current user organisation when checking permissions in the auth plugin
Fixes #320

Review listAllUserPolicies (and fix exposed bugs)

---

database/migrations/001.do.sql
database/migrations/002.do.sql

@marcopiraccini alerted us that postgrator is giving some errors when applying the new migrations. 
postgrator will create a md5 from each migration file and if we change it (spaces and such) it will complain 
ie:
```
verifying checksum of migration 001.do.sql
Error in runMigrations() while verifying checksums of existing migrations
Error: For migration [1], expected MD5 checksum [087575231b8a994ec3f1801e7b5c43b5] but got [58a6432ebb6890810f7ee97a6922399b]
```

Update migration to fix problems for who was already using them

---

lib/core/lib/ops/utils.js
test/integration/endToEnd/teams.test.js
test/integration/endToEnd/users.test.js
test/integration/teamOps.test.js

The PR fixes the foreign key returned error for cases when the ID is invalid for operations like add policy, user, replace policy, replace user

invalid user policy id handling

---

database/init.js
database/testdata/fixtures.sql
lib/core/config/config.auth.js
lib/core/index.js
lib/core/lib/ops/userOps.js
lib/core/lib/ops/validation.js
lib/plugin/routes/public/users.js
lib/plugin/security/authorization.js
lib/plugin/security/hapi-auth-service.js
lib/plugin/security/hapi-auth-validation.js
test/integration/authorization/users.test.js
test/integration/endToEnd/users.test.js

This PR adds two new endpoint:
* `POST /users/{id}/teams` to replace user's teams
* `DELETE /users/{id}/teams` to remove user from all her teams
The tricky operation here was checking that the caller had the right permission on all teams because if the caller is not allowed to manipulate a user inside a certain team the operation should fail.
To achieve this we had to add a new function in the auth scheme object: `payload` (doc [here](https://github.com/hapijs/hapi/blob/master/API.md#serverauthschemename-scheme)). We need that function because we will get the teams (for `POST /users/{id}/teams`) from the request payload, but [the payload is not yet parsed when the `authenticate` function is called](http://freecontent.manning.com/hapi-js-in-action-diagram/).
This PR add also a new module …

Add two new users endpoint replace/delete teams

---

lib/core/lib/ops/organizationOps.js
lib/core/lib/ops/userOps.js
lib/core/lib/ops/validation.js
test/integration/endToEnd/users.test.js
test/integration/organizationOps.test.js
test/integration/policyOps.test.js
test/integration/security/sqlinjection.test.js
test/integration/teamOps.test.js
test/integration/userOps.test.js

Implements: https://github.com/nearform/labs-authorization/issues/360
- Cleaned up the Joi validation file,
- Added Joi validation and tests for the Name field on orgs, users, teams and policies,
- Team parent id Joi validation,
- Added 400 bad request for cases when trying to create element with existing id. Added tests and error creation for orgs, users, teams and policies.

Issue 360 existing organization id error

---

docs/authmodel.md
docs/authorization-introduction.md
test/integration/endToEnd/fullOrgStructure.test.js
test/utils.js

First draft of sample code and documentation that shows how to model two teams of SuperUsers that through their attached policies limit the SuperUser access across organizations.
/cc @p16

SuperUsers with limited access across organizations

---

database/migrations/003.do.sql
database/migrations/003.undo.sql
lib/core/lib/ops/validation.js
package.json
test/integration/organizationOps.test.js
test/integration/policyOps.test.js
test/integration/teamOps.test.js
test/integration/userOps.test.js

Implements: https://github.com/nearform/labs-authorization/issues/374
Updates also the organization_policies.org_id field to 128 to match the organizations.id
/cc @marcopiraccini

increase user.name length, fix org_policies.org_id

---

README.md
package.json

Fixes #380, but showed that #383 should be fixed as well for testing it on popular linux distributions ( at least `ubuntu`-based plus `arch`-based ones).

Issue 380 fix : move `postinstall` script to `presecurity:test`

---

README.md
security/runner.js

#380 should be merged before.
This code checks if `python2` or `python` are available from the path, and if so checks if they are valid Python 2.x implementation.
If so, the first one that matches those conditions will be used to run `sqlmap` during `security:test` npm script

Issue 383 run `sqlmap` with `python2` or `python`

---

CHANGES.md
README.md
docs/how-to-release.md
package.json
test/integration/endToEnd/authorization.test.js

Some badges/url do not exist yet :
- https://coveralls.io/github/nearform/udaru?branch=master still point to a `404`

Update branding to udaru everywhere

---

lib/core/lib/mapping.js
lib/core/lib/ops/teamOps.js
lib/server/start.js
package.json

Hi, 
when i started udaru as service i got it crashing because another service was already running on default port `8080`. Unfortunately i didn't get any message on why udaru crashed. I've added a new  error handling while spinning up the server so that if that situation happen again you'll see something like this:
```
udaru git:(master) npm start
> udaru@2.0.1 start /Users/michele/Github/udaru
> node lib/server/start.js
Failed to start server: listen EADDRINUSE 127.0.0.1:8080
➜  udaru git:(master) ✗
```
I also fixed pending linting errors.

Added error handling for server startup 

---

.gitignore
.travis.yml
npm-shrinkwrap.json
package.json
scripts/getSwaggerJson.js

This PR adds a new command `npm run swagger-gen`. The result is a static version of the swagger docs for Udaru placed in `docs/udaru-swagger-site`
I've also added this command to `travis.yml`
There is a small script (`scripts/getSwaggerJson.js`) that spins up the Udaru server and injects a request to get the `swagger.json` file. The JSON is simply logged to stdout.
This JSON is then piped into a CLI tool I wrote called [swagger-gen](http://npm.im/swagger-gen).
The `npm run swagger-gen` command is simply running `node scripts/getSwaggerJson.js | swagger-gen -d docs/udaru-swagger-site`. The `-d` flag specifies the output destination.

Add Script to generate static swagger API docs

---

lib/server/index.js

By default the Swagger definitions are grouped by path prefix e.g. `/cats` `/dogs`.
Every path except `/ping` in Udaru is prefixed with `/authorization` and the result is a giant unorganized list of paths shown in the image:
This PR adds a tiny config change passed to `hapi-swagger` and the result of that is something like this:
Now this does create duplication e.g. `/authorization/organizations` is listed under the `organizations` tag heading and it's also listed under the `service` tag heading. But really I find most of the tags are pretty useless so I propose we simplify the whole thing down, maybe to a maximum of two tags:
1. A tag that identifies the endpoint by function e.g. `organization` or `users` or `teams`
2. A tag that makes the distinction between public/private or admin/user …

hapi-swagger - group docs by tags

---

docs/swagger/index.html
npm-shrinkwrap.json
package.json

So I spent some time updating the [swagger-gen](http://npm.im/swagger-gen) module to have a new `--no-try-out` option. Which basically injects some extra CSS into the UI which stops the 'Try it out' buttons being rendered. This PR makes use of that new option and also updates the docs accordingly.
Example Screenshot:

use --no-try-out option with swagger-gen

---

README.md
docs/index.html

Because of the funny way docsify handles relative links within a repo, sometimes they get a little messed up. e.g. the docsify sees the relative link to `database/migrations` and tries to render a `database/migrations.md` file.
Also, because the README is in the root of the repo but docsify operates in the context of the `/docs` folder this causes some issues too. This PR changes some links in the README file to use absolute links instead.

Fix Links that don't work in the docsify site

---

bench/access.bench.js
docs/example.md
docs/overview.md
lib/core/config/config.auth.js
lib/core/index.js
lib/core/lib/ops/authorizeOps.js
lib/core/lib/ops/iam.js
lib/core/lib/ops/validation.js
lib/plugin/routes/public/authorization.js
lib/plugin/swagger.js
test/integration/authorization/authorization.test.js
test/integration/endToEnd/authorization.test.js
test/unit/iam/actions.test.js
test/unit/iam/basic.test.js
test/unit/iam/ownership.test.js
test/unit/routes/public/authorization.test.js

This new endpoint allows us to list the actions a user can perform on a list of resources
When calling, the endpoint looks like this:
```
GET /authorization/list/some-user-id?resources=foo&resources=bar&resources=baz
```
which will return a list like this:
```
[
{
resource: 'foo',
actions: ['Read']
},
{
resource: 'bar',
actions: ['*']
},
{
resource: 'baz',
actions: []
}
]
```
__Small Note on Validation__
The endpoint will still work if only one resource is passed in the querystring.
The Joi schema for resources uses ['Array.single()`](https://github.com/hapijs/joi/blob/v10.6.0/API.md#arraysingleenabled) which will optionally accept a single value and put it in an array. e.g.
```
GET /authorization/list/some-user-id?resources=foo
```
will result in `request.query.resources === ['foo']` …

Endpoint for listing allowed actions on Multiple Resources

---

lib/core/index.js
lib/core/lib/db/index.js
lib/plugin/index.js
lib/plugin/routes/private/policies.js
lib/plugin/routes/public/authorization.js
lib/plugin/routes/public/monitor.js
lib/plugin/routes/public/organizations.js
lib/plugin/routes/public/policies.js
lib/plugin/routes/public/teams.js
lib/plugin/routes/public/users.js
lib/plugin/security/authorization.js
lib/plugin/security/hapi-auth-service.js
lib/plugin/security/hapi-auth-validation.js
lib/policiesLoader.js
package-lock.json
package.json
scripts/init.js
test/factory.js
test/unit/db.test.js

The purpose of this PR is to remove the dependency on a common Udaru Core instance passed as parameter to routes and other functionality at the plugin level.
The changes are the following:
- All routes expect a decorated Udaru instance on request,
- Routes Joi validation is used by directly requiring the Joi validation files. Validation is not gathered any more from a common Udaru instance,
- The authorization checks made at route level are using the Udaru core instance decorated on request
- The service has an option with wich the Udaru core decoration can be disabled (it is enabled by default). This allows Udaru core to be passed from outside from the service level.
- Added a small change on the Factory used by tests to generate data in db. As it was using a default Udaru core (with …

Remove core instance dependency at plugin level

---

database/migrations/004.do.sql
database/migrations/004.undo.sql
docs/overview.md
lib/core/lib/mapping.js
lib/core/lib/ops/organizationOps.js
lib/core/lib/ops/policyOps.js
lib/core/lib/ops/teamOps.js
lib/core/lib/ops/userOps.js
lib/core/lib/ops/utils.js
lib/core/lib/ops/validation.js
lib/plugin/swagger.js
package.json
test/factory.js
test/integration/authorizeOps.test.js
test/integration/endToEnd/organizations.test.js
test/integration/endToEnd/teams.test.js
test/integration/endToEnd/users.test.js
test/integration/organizationOps.test.js
test/integration/policyOps.test.js
test/integration/security/sqlinjection.core.test.js
test/integration/teamOps.test.js
test/integration/userOps.test.js

Policy templates are implemented as regular policy with variables similar to regular PBAC variables.
However, it is possible to fix the value of those variables when a policy is assigned to a user, team or organisation.
This PR makes 3 changes:
- endpoints that assign policies now support passing variables
- endpoints that return assigned policies now return variables as well
- policies retrieved for an authorization check are now parsed and variables are interpolated before being feeded into PBAC
This is the first step required to make policies shared across organisation and is meant to allow customisation of the policies.
Next step is to build a mechanism to actually share the policies and make them visible to all organisations.

Introduce policy templates

---

database/migrations/005.do.sql
database/migrations/005.undo.sql
database/testdata/fixtures.sql
docs/overview.md
lib/config/auth.js
lib/core/index.js
lib/core/lib/ops/policyOps.js
lib/core/lib/ops/utils.js
lib/core/lib/ops/validation.js
lib/plugin/routes/private/policies.js
lib/plugin/routes/public/policies.js
lib/plugin/security/authorization.js
lib/plugin/security/hapi-auth-validation.js
package.json
test/factory.js
test/integration/authorization/policies.test.js
test/integration/authorization/testBuilder.js
test/integration/endToEnd/policies.test.js
test/integration/organizationOps.test.js
test/integration/policyOps.test.js
test/integration/teamOps.test.js
test/integration/userOps.test.js

Shared policies aren't bounded by a single organization, but available to all the organizations on the same database.
They can be assigned to any user or team of any organization

Introduce shared policies

---

lib/plugin/index.js

When the decorateUdaruCore flag is set on false no need to create an Udaru Core instance. This removes the need to pass a db config when the flag is on false.
The flag is set on false when the Udaru Core instanced is decorated from outside.

Do not create Udaru instance when no need to decorate

---

lib/core/lib/ops/utils.js
lib/plugin/index.js
package-lock.json
test/integration/policyOps.test.js

In case of policies with variables you could assign the same policy to the same user but having different variables. The checkPoliciesOrg was failing because in this case where you have duplicate policy IDs the query returns less results that the policy array as the query does not return duplicate entries.
Added also a fix on the `decoreateUdaruCore` retrieval, `config` was of type Reconfig and confg properties are accessed using `.get(property)`

Fix multi variable policies

---

CHANGES.md
lib/core/lib/ops/userOps.js
lib/plugin/routes/public/users.js
package-lock.json
package.json
test/integration/endToEnd/users.test.js
test/integration/userOps.test.js

Addresses https://github.com/nearform/udaru/issues/453
This unifies the implementation with the ones made at similar endpoints, like get users:
- the page is what the user sends or 1 by default
- the limit is what the user sends or 100 by default (100 is set in config)
- the answer is an object containing: page used for query, limit used for query, the total records found (not only the returned ones), the data result of the current query
There seems to be some implementation on `Get team users` that is not consistent with the other endpoints, will open an issue to investigate it.

fix: allow empty results when the user is in no teams

---

CHANGES.md
lib/core/lib/ops/iam.js
package-lock.json
package.json

snyk vulnerability meant we neede to updated pbac
latest version of pbac updated today to update lodash dependency...
when we updated pbac, tests failed as StringLike in pbac takes params in opposite order to what we passed originally...
Swapped below... I don't think this has wider implications and should solve this issue at least.

updated pbac version, iam.js also changed

---

lib/plugin/routes/public/users.js

The endpoint should expose a get params functions that when called by the resource builder should provide the user id. In this case the resource was `.../WONKA/*/*` instead of `.../WONKA/*/userId`

Add request id for the resource builder

---

CHANGES.md
database/migrations/006.do.sql
database/migrations/006.undo.sql
database/migrations/007.do.sql
database/migrations/007.undo.sql
package-lock.json
package.json

public schema removed from migration scripts... this will cause a bad credentials error if migration to 7 does not work

removing public schema from migration scripts

---

lib/config/auth.js
lib/core/index.js
lib/core/lib/ops/teamOps.js
lib/core/lib/ops/validation.js
lib/plugin/routes/public/teams.js
lib/plugin/swagger.js
test/integration/teamOps.test.js

Add support for searching teams by name or description. 
Endpoint: `/authorization/teams/search` that takes parameters:
_headers_: `authorization`, `org` 
_query_:  `query`
Completes the team search support (based on PR #463)
@dberesford @mihaidma

Search teams

---

docs/overview.md
packages/udaru-core/database/loadVolumeData.js
packages/udaru-core/lib/ops/authorizeOps.js
packages/udaru-core/lib/ops/iam.js
packages/udaru-core/lib/ops/validation.js
packages/udaru-core/package.json
packages/udaru-core/test/integration/authorizeOps.test.js
packages/udaru-hapi-plugin/routes/public/authorization.js
packages/udaru-hapi-plugin/test/endToEnd/authorization.test.js
packages/udaru-hapi-server/README.md
packages/udaru-hapi-server/bench/util/loadVolumeData.js
packages/udaru-hapi-server/package-lock.json
packages/udaru-hapi-server/package.json
packages/udaru-test/utils.js

@dberesford @mihaidma 
I rebased this branch with master, the context stuff is in here and I added some testing around it, as well as tests around not allowing reserved keywords as variable names in policy instances.
Volume db and autocannon volume tests can be run now from hapi-server-plugin module too.

Context policy variable evaluation

---

package.json
packages/udaru-core/package.json
packages/udaru-hapi-16-plugin/package.json
packages/udaru-hapi-plugin/package.json
packages/udaru-hapi-server/package.json

Also updated the `homepage` links. 
Note this list was authgenerated using https://www.npmjs.com/package/contributor.
Would be much easier to maintain going forward to just have a `contributors.md` file in the root package.

 Updated contributors in package.json files

---

.travis.yml
packages/udaru-core/.labrc.js
packages/udaru-core/package.json
packages/udaru-hapi-16-plugin/.labrc.js
packages/udaru-hapi-16-plugin/package.json
packages/udaru-hapi-plugin/.labrc.js
packages/udaru-hapi-plugin/package.json

I ran into issues here with global leaks in core and hapi-16-plugin, we don't have the issue when using lab15 with hapi 17. I tried upgrading dependencies etc, and I removed all tests and the leaks were still occurring so it doesn't seem to be a runtime udaru issue but rather some issue with node10/lab14/dependencies.  I've put in two globals for the items URL & URLSearchParams into .labrc.js files to bypass... these should be removed once lab is upgrade for core and hapi-16, they're not necessary for hapi 17 plugin, which uses lab 15+
I've taken the command line args from package.json lab entries (except for coverage docs) in favour of using labrc.js file for consistency (there's no point having global exclusions polluting package.json files)

node 10 check

---

packages/udaru-core/lib/ops/policyOps.js
packages/udaru-core/lib/ops/teamOps.js
packages/udaru-core/lib/ops/userOps.js
packages/udaru-core/lib/ops/utils.js
packages/udaru-core/test/integration/teamOps.test.js
packages/udaru-core/test/integration/userOps.test.js
packages/udaru-core/test/unit/utils.test.js
packages/udaru-hapi-16-plugin/test/endToEnd/teams.test.js

I've centralized the escaping here and transform of the query into utils and created some unit tests for that function to sanity check it...
user, policy and team search now all call to this
I'm hoping i've caught everything here, putting each entry into single quotes means characters in there won't interfere with the operators e.g. 'AT&T' would not evaluate as 'AT' & 'T' and : character that is reserved for commands like substring :*  shouldn't cause errors if parts of names.
When using quotes around components of a string, things like single quotes and backslashes must be escaped hence the replace expressions.
I put the :* after every component also
I added several integration tests then in core and a single test in hapi 16 server to verify a search for name with colon in it works
Some …

tsquery escaping

---

docs/contributing.md
docs/example.md
package.json
packages/udaru-core/database/migrations/009.do.sql
packages/udaru-core/database/migrations/009.undo.sql
packages/udaru-core/lib/mapping.js
packages/udaru-core/lib/ops/validation.js
packages/udaru-core/test/integration/organizationOps.test.js
packages/udaru-core/test/integration/policyOps.test.js
packages/udaru-core/test/integration/teamOps.test.js
packages/udaru-core/test/integration/userOps.test.js

underscores now whitelisted in all fields to cater for backward compatibility for teams in particular (as underscores were previously enforced).  
Migration script updated with regex to cater for underscore and also validation.js in core updated too for all ids
As team paths only allow underscores and alphanumerics (ltree restriction), we must convert hyphens in ids to underscores in the path.  this may cause clashes and undesired behaviour so an extra constraint was added to ensure path is unique in migration script. 
a test case was added to ensure the database cannot contain two teams with the same path when ids with hypens and underscores convert to to the same path.
paths will be returned with hypens from a user perspective (for easier use of API when we eventually expose calls that …

allow underscores on id fields for backward compatibility

---

package.json
packages/udaru-hapi-16-plugin/test/authorization/authorization.test.js
packages/udaru-hapi-16-plugin/test/endToEnd/authorization.test.js
packages/udaru-hapi-plugin/lib/routes/authorization.js
packages/udaru-hapi-plugin/test/authorization/authorization.test.js
packages/udaru-hapi-plugin/test/endToEnd/authorization.test.js

Addresses issue #555
Also includes: 
- add tests
- fix existing tests which were succeding because wrongly implemented

Expose batch authorization in Hapi 17 plugin

---

packages/udaru-core/lib/ops/organizationOps.js
packages/udaru-core/lib/ops/teamOps.js
packages/udaru-core/test/integration/organizationOps.test.js
packages/udaru-core/test/integration/teamOps.test.js

Hi @mihaidma 
Just a small PR for Udaru.
I had a small issue where calling:
```
await udaru.organizations.create(organization, { createOnly: true })
```
would ignore my 2 param `{ createOnly: true }`.
My current working workaround is:
```
await udaru.organizations.create(organization, { createOnly: true }, true)
```
to skip the missing callback check.
But I thought I would contribute back to fix this small issue.
Let me know if you have any question.

Organization & teams create callback handling

---

packages/udaru-core/lib/ops/organizationOps.js
packages/udaru-core/lib/ops/teamOps.js
packages/udaru-core/lib/ops/userOps.js

Replace `undefined` params with `null` before constructing the `SQL` object.
This prevents throwing an error from inside `@nearform/sql` >= v1.3.1.
Fixes issue #565

replace nullable sql field params

---

package.json

Removes an invalid bin reference to a non-existent package as commented in issue #417.
Probably stayed there after v4.x => v5.x.

remove bin ref to non-existing package

---

.travis.yml
docs/contributing.md
package.json
packages/udaru-core/package.json
packages/udaru-hapi-16-plugin/package.json
packages/udaru-hapi-plugin/package.json
packages/udaru-hapi-server/package.json

Drops support for Node v6 by: 
- changing minimum version to v8
- upgrading dependencies
- change test commands
- updating docs

Deprecate Node v6

---

packages/udaru-core/config.js
packages/udaru-core/package.json

Since v3.3.0 of reconfig, it drops functions that were passed into it. See issue #526.
Example:
```js
// template
{
resources: {
func1: function () {}
}
}
// becomes
{
resources: {
func1: {}
}
}
```
This was not the case in v3.2.0. Dependency was locked at the old version to prevent breaking Udaru. To still be able to upgrade to newer versions of the depencency, a fix is needed to restore the functions from `_rawConfig` => `_config`.

Fix reconfig functions

---

packages/udaru-hapi-plugin/lib/authentication.js
packages/udaru-hapi-plugin/lib/authorization.js
packages/udaru-hapi-plugin/lib/routes/policies.js
packages/udaru-hapi-plugin/package.json
packages/udaru-hapi-plugin/test/authorization/authorization.test.js
packages/udaru-hapi-plugin/test/authorization/organizations.test.js
packages/udaru-hapi-plugin/test/authorization/policies.test.js
packages/udaru-hapi-plugin/test/authorization/teams.test.js
packages/udaru-hapi-plugin/test/authorization/users.test.js
packages/udaru-hapi-plugin/test/edgeCases.test.js
packages/udaru-hapi-plugin/test/endToEnd/authorization.test.js
packages/udaru-hapi-plugin/test/endToEnd/fullOrgStructure.test.js
packages/udaru-hapi-plugin/test/endToEnd/monitor.test.js
packages/udaru-hapi-plugin/test/endToEnd/organizations.test.js
packages/udaru-hapi-plugin/test/endToEnd/policies.test.js
packages/udaru-hapi-plugin/test/endToEnd/teams.test.js
packages/udaru-hapi-plugin/test/endToEnd/users.test.js
packages/udaru-hapi-plugin/test/security/sqlinjection.test.js
packages/udaru-hapi-plugin/test/test-server.js
packages/udaru-hapi-plugin/test/testBuilder.js

When running `npm audit` on my node project I received:
```
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │ …
```

Update udaru-hapi-plugin dependencies to the latest @hapi scope to fix a vulnerability issue
