nearform/udaru

service/package.json

When iam-js repo is public we can merge this.
/cc @feugy

Update iam-js repo

---

service/test/routes/public/teamsTest.js

Fixing teams id in tests

---

scripts/init/database/install_000.js
scripts/init/database/install_001.js

Fix migration script to work with config values

---

service/lib/ops/organizationOps.js
service/lib/ops/policyOps.js
service/lib/ops/teamOps.js
service/lib/ops/userOps.js
service/lib/ops/utils.js
service/test/endToEnd/policiesTest.js
service/test/endToEnd/teamsTest.js
service/test/endToEnd/usersTest.js

Ref. issue #262 
/cc @feugy @marcopiraccini

Add user, team and policy id handling for duplicated id

---

service/lib/ops/policyOps.js
service/lib/ops/teamOps.js
service/test/lib/integration/userOpsTest.js

seclude policy ops by org

---

test/endToEnd/authorization/testBuilder.js
test/endToEnd/authorization/usersTest.js
test/factory.js

I'm spending quite a long time on these tests, and I'd like to get some early feedback on: 
1- do we even need this kind of tests?
2- is the style ok?
The main reason we started looking into authentication tests was to make sure we are actually enforcing permissions and policies check on our endpoints.
However, the more I write them the more I have two doubts that seems smells of bad tests to me:
a- we are basically testing a config (did we place the correct action in the auth config?)
b- the special cases would be better suited as unit tests for the auth middleware (i.e. the teams case) or for aim-js (wildcards)
I still find some value in these tests because:
a- I don't think we are actually testing a config as per point `a`, because there could be multiple configurations that lead to …

Add authentication tests

---

src/routes/private/policies.js
src/routes/public/teams.js
test/endToEnd/policiesTest.js
test/endToEnd/teamsTest.js

Fixes error when team id was an empty string

---

test/endToEnd/authorization/authorizationTest.js
test/endToEnd/authorization/organizationsTest.js
test/factory.js

Also expand factory to support organizations

Expand authorization tests to authorization and organizations routes

---

README.md
src/routes/headers.js
src/routes/public/authorization.js
src/routes/public/monitor.js
src/routes/public/organizations.js
src/routes/public/policies.js
src/routes/public/teams.js
src/routes/public/users.js
src/swagger.js

To not keep the branch too much and avoid too many git rebases I PR the doc changes.
After merge will continue with the other points of the documentation task.

Documentation review

---

src/security/hapi-auth-service.js
src/security/hapi-auth-validation.js
test/endToEnd/authorization/usersTest.js

Load the user teams and build multiple resource, including one with a
"*" team

Make auth tests on user teams work

---

src/lib/ops/teamOps.js
src/routes/public/teams.js
src/swagger.js
test/endToEnd/teamsTest.js
test/lib/integration/teamOpsTest.js

[Implemented like described in the issue](https://github.com/nearform/labs-authorization/issues/313)

unified teams users pagination

---

src/routes/private/policies.js
src/routes/public/authorization.js
src/routes/public/organizations.js
src/routes/public/policies.js
src/routes/public/teams.js
src/routes/public/users.js
src/swagger.js
src/wiring-hapi.js

Enhanced the returned model displayed on Swagger.
Added `valid('Allow', 'Deny')` on the Statement Effect.

returned result model

---

README.md

Instead of David which looks dead

Snyk on readme

---

README.md
docs/authorization-introduction.md
docs/reference/spec.md

Made a first version of doc, not satisfied yet with the level of detail provided, will add more info.
Feedback is welcome.

Authorization documentation

---

.gitignore
README.md
docs/authorization-introduction.md
docs/sqlinjection.md
package.json
security/fixtures/injection-endpoints.json
security/runner.js
test/integration/security/sqlinjection.core.test.js
test/integration/security/sqlinjection.md
test/integration/security/sqlinjection.test.js

Finalized the manual and automatic (using the `sqlmap` tool) injection check. This step contains documentation on how the evaluation was made, made helper tests for the manual check.
One step remained to do: add npm script to automate the sql map automatic checks.
Any feedback is welcome.

Test sql injection

---

database/init.js

Remove not used admin account

---

lib/core/config/config.auth.js
lib/core/index.js
lib/core/lib/ops/organizationOps.js
lib/core/lib/ops/policyOps.js
lib/core/lib/ops/userOps.js
lib/core/lib/ops/utils.js
lib/core/lib/ops/validation.js
lib/plugin/routes/public/organizations.js
lib/plugin/swagger.js
package.json
security/runner.js
test/integration/authorization/organizations.test.js
test/integration/endToEnd/organizations.test.js
test/integration/organizationOps.test.js

Added 4 org operations: https://github.com/nearform/labs-authorization/issues/356
Added a small fix for the sqlmap script in package json
Working separately on adding authorization tests as the test framework needs adding support for policies attached to orgs.
/cc @p16

Issue 356 organization policies apis

---

lib/core/lib/ops/policyOps.js
test/factory.js
test/integration/authorization/organizations.test.js
test/integration/policyOps.test.js

- Added org policies support in test factory,also fixed factory issues. Addresses: https://github.com/nearform/labs-authorization/issues/363,
- Added remove org policies in the policies ops: https://github.com/nearform/labs-authorization/issues/364

factory fixes, policy ops tests, org authorization tests

---

test/integration/authorizeOps.test.js
test/integration/policyOps.test.js

inherited tests implementation: https://github.com/nearform/labs-authorization/issues/367

inherited policies tests

---

test/integration/authorization/organizations.test.js

Add authorization tests for the organization policy management endpoints: https://github.com/nearform/labs-authorization/issues/370

org policy management authorization tests

---

.travis.yml
README.md
bench/util/runner.js
database/init.js
database/loadTestData.js
database/migrate.js
docs/authmodel.md
docs/authorization-introduction.md
lib/core/lib/ops/organizationOps.js
lib/core/lib/ops/policyOps.js
lib/core/lib/ops/teamOps.js
lib/core/lib/ops/userOps.js
lib/plugin/config/index.js
lib/policiesLoader.js
lib/server/start.js
npm-shrinkwrap.json
scripts/init.js
security/runner.js

* console.log -> console.error for errors
* Minor corrections to readme and typo's in comments
* Reduce verbosity of hapi-pino logger, info too verbose. Warn is now the default.

Minor tweaks..

---

lib/plugin/index.js

Fixes https://github.com/nearform/udaru/issues/420

call next after routes are registered

---

lib/core/lib/ops/policyOps.js
test/integration/endToEnd/authorization.test.js
test/integration/policyOps.test.js

Implemented tests to reproduce and added a fix for: https://github.com/nearform/udaru/issues/428

Issue 428 not existing user gets authorized

---

scripts/init.js

Updated the `scripts/init.js` script with latest Udaru Core changes so that it works again.
Fixes https://github.com/nearform/udaru/issues/431

Update db init script

---

CHANGES.md
lib/config/auth.js
lib/core/index.js
lib/core/lib/ops/userOps.js
lib/core/lib/ops/validation.js
lib/plugin/routes/public/users.js
lib/plugin/swagger.js
test/integration/endToEnd/users.test.js
test/integration/userOps.test.js

Added an enpoint that returns all the teams that the user belongs to.

WIP - Get user teams

---

docs/example.md

typo fixes from https://github.com/nearform/udaru/pull/551

fix example doc typos

---

CHANGES.md
README.md
packages/udaru-core/package.json
packages/udaru-hapi-16-plugin/package.json
packages/udaru-hapi-plugin/package.json
packages/udaru-hapi-server/package.json

Merged and tested:
https://github.com/nearform/udaru/pull/560
Bumped some packages
Fix docs

Release preparations 5.2.3

---

package.json

Release preparations 5.3.0

---

.travis.yml
packages/udaru-core/.labrc.js
packages/udaru-hapi-16-plugin/.labrc.js
packages/udaru-hapi-16-plugin/test/edgeCases.test.js
packages/udaru-hapi-plugin/.labrc.js
packages/udaru-hapi-server/.labrc.js

Adds automated tests to Travis and resolves some issues with the test runs for Node v12.
Resolves issue #567

Node 12 support

---

README.md
packages/udaru-core/README.md
packages/udaru-hapi-16-plugin/README.md
packages/udaru-hapi-plugin/README.md
packages/udaru-hapi-server/README.md

update broken badges and links

Fix broken links

---

packages/udaru-core/config.js
packages/udaru-core/test/integration/authorizeOps.test.js
packages/udaru-core/test/integration/policiesLoader.test.js
packages/udaru-core/test/unit/hooks.test.js
packages/udaru-core/test/unit/iam/actions.test.js
packages/udaru-core/test/unit/mapping.test.js
packages/udaru-core/test/unit/utils.test.js

Still a work in progress to add testing and improve coverage.
PR to let Travis process changes on coverage.

Improve testing and coverage
